# Generated by Django 5.1.6 on 2025-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_social_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/mehmete_ekiz/', max_length=50),
        ),
    ]
